### PR TITLE
Consider scala patch version for scalac-scoverage-plugin

### LINKED ISSUE #94: Consider using Scala's patch version to determine the artifactId of the scalac-scoverage-plugin
Hi,

We are currently trying to use the `check` goal with the scoverage-maven-plugin version: 1.4.1 and Scala version 2.12.13

When configuring scalacPluginVersions with value: `1.4.1` or `1.4.2` we get the following error:
`java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/report`

When using scalacPluginVersions: `1.4.3` or greater we get an error similar to the following:
`Could not find artifact org.scoverage:scalac-scoverage-plugin-2.12:jar:1.4.7 in <internal-repository>`); this is during the `pre-compile stage`

Based on this [sbt-scoverage issue](https://github.com/scoverage/sbt-scoverage/issues/319) we gather that the Scala 2.12.13 compiler not backwards compatible (resulting in the 1st error). I'm assuming this is why the scala-scoverage-plugin has begun to include Scala's patch version as part of it's artifactId.
Additionally, based on [SCoveragePreCompileMojo](https://github.com/scoverage/scoverage-maven-plugin/blob/master/src/main/java/org/scoverage/plugin/SCoveragePreCompileMojo.java#L250) we gather that the plugin ignores Scala's patch version when determining which version of the scalac-scoverage-plugin to use (resulting in the 2nd error).

If the above seems correct and reasonable, would you consider updating the maven plugin so that we are able to use a newer version of the scalac-scoverage-plugin - allowing us to use SCoverage with Scala 2.12.13?

Please let me know if the provided information is not sufficient.

Thanks,
Stewart

### PR DESCRIPTION
**Pull request by sumeetgajjar**
This PR implements the approach proposed in #94. Post this it would be possible to use the maven plugin with Scala 2.12.13+

With this PR now plugin artifact lookup logic is done like below

1 First look for artifact having a name like scalac-scoverage-plugin_2.12.14 i.e. use the full version of Scala lib used in the project
2 If that artifact is not found look for scalac-scoverage-plugin_2.12

For this to work completely you still need to specify the scalacPluginVersion property. For example, with Scala 2.12.14 we need version [scalac-scoverage-plugin - 1.4.8](https://github.com/scoverage/scalac-scoverage-plugin/releases/tag/v1.4.8)

Fixes #94

(cherry picked from commit bc925fdf1ae07c333da35b2cb939e8d18df66fab)

### CODE REVIEW

**Comment by sumeetgajjar** [comment]
This is a cherry-pick of #95. There's been no movement on #95 from Aug 2021, so I thought I would pick this up and address the reviewer's comment.

**Comment by sumeetgajjar** [comment]
@gslowikowski @sksamuel @ckipp01 could you please take a look at this PR?

**Comment by sumeetgajjar** [comment]
The CI build error for windows 8 is due to a connection reset while fetching the maven-surefire-plugin, which is unrelated to this change.
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test 
..
..
Connection reset -> [Help 1]
```
I've pushed an empty commit to trigger CI re-run.

**Comment by gslowikowski** [comment]
Merged the original PR #95

**Pull request closed without merging**
